# This is a basic workflow to help you get started with Actions

name: Inventory Update

# Controls when the action will run. 
on:
  schedule:
    - cron: '30 5 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: refresh inventory
      id: inventory_refresh
      run: |
        python utils/refresh_inventory.py
    
    - uses: EndBug/add-and-commit@v5 # You can change this to use a specific version
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'inventory/instances.json'

        # The name of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_name: TuxieDev

        # The email of the user that will be displayed as the author of the commit
        # Default: author of the commit that triggered the run
        author_email: tuxiedev@gmail.com

        message: 'Update inventory'

        # The flag used on the pull strategy
        # Default: '--no-rebase'
        pull_strategy: '--rebase'

        # Whether to push the commit and, if any, its tags to the repo (only `true` and `false` are accepted)
        # Default: true
        push: true

      env:
        # This is necessary in order to push a commit to the repo
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      
